### ISSUE TITLE
Why is it not recommended for SetState/GetState?

### ISSUE THREAD

**Issue by s-n-1-0** [neurotechcenter/UnityBCI2000#8]
Hi, I am working on a Japanese tutorial for this library.

Why is passing data through states deprecated?

https://github.com/neurotechcenter/UnityBCI2000/blob/e79f603f4852e68e5c9d30eb248d08f44174b867/UnityBCI2000.cs#L146-L153

**Comment by s-n-1-0** [comment]
@Personator01

**Comment by Personator01** [comment]
Use of states was not recommended as State variables have a temporal resolution limited to the block size, which is often in the hundreds of milliseconds, whereas Events have a temporal resolution of the sample rate, which is much faster. States are usually used to record the current experiment state on a block level for experiments which are synchronous to BCI2000's event loop, and as such, are less well-suited to use with an external Unity experiment. 

The method should work, but that part of the code has been unmaintained and untested since it was written. The new version 2.0.0 of UnityBCI2000 instead uses BCI2000RemoteNET directly, and its new version has support for state variables, the code for which can be seen at https://github.com/neurotechcenter/BCI2000RemoteNET/blob/main/BCI2000Remote.cs

We recommend migration to the new version, as it was rewritten from the ground up and should be more reliable and maintainable. However, migration is non-trivial and the new version is not yet fully documented. Apologies if this sets you back, I should probably have announced the rewrite earlier.

**Comment by Personator01** [comment]
If you have already done work on the tutorial for version 1.0, we can provide the necessary support for migrating it to 2.0 so that this release is less of a rugpull.

**Comment by s-n-1-0** [comment]
Thanks for your answer. It helps to know why.
For now, I will write the tutorial in version 1.0 (and states is deprecated even in 1.0!).

I look forward to the official release of 2.0.

**Comment by Personator01** [comment]
Just for your information, version 2.0 is released in beta form as of yesterday, and it should be in its final release state save for bugfixes. A non-beta release should happen this week.
